### ISSUE TITLE
Room for improvements

### ISSUE THREAD

**Issue by mathcrln** [mathcrln/todo-dashboard#1]
## CSS Improvements 
- [x] Fix the spacing of the menu
- [x] Fix the planning section (the spaces taken by each "task")
- [x] Fix the spacing to the right on mobile,
- [x] Configure the sticky menu on mobile,

## Syntax
- [x] Rewrite the code in SCSS
- [x] Clean the code
- [x] Translate to english

## New Features
- [x] Make the website **responsive** on mobile
- [x] Make the website responsive on Tablet
- [x] Implement a **dark mode**
- [x] Implement some **interactions** (with JS)

**Comment by KokosnussDEV** [comment]
When the Interactions are added, this will be one of the best designs I've seen so far
